language: python
python:
    - "3.5"
    - "3.6"

before_install:
    - "chmod +x tests/cell_tests.py"
    - "chmod +x tests/maze_tests.py"
    - "chmod +x tests/maze_manager_tests.py"
    - "chmod +x tests/maze_viz_tests.py"
    - "chmod +x tests/solver_tests.py"

install:
    -  "pip install -r requirements.txt"

script:
    - "python -m unittest tests/cell_tests.py"
    - "python -m unittest tests/maze_tests.py"
    - "python -m unittest tests/maze_manager_tests.py"
    - "python -m unittest tests/maze_viz_tests.py"
    - "python -m unittest tests/solver_tests.py"
